Document: nfs-application-deploy-tool
Title: Debian nfs-application-deploy-tool Manual
Author: <insert document author here>
Abstract: This manual describes what nfs-application-deploy-tool is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nfs-application-deploy-tool/nfs-application-deploy-tool.sgml.gz

Format: postscript
Files: /usr/share/doc/nfs-application-deploy-tool/nfs-application-deploy-tool.ps.gz

Format: text
Files: /usr/share/doc/nfs-application-deploy-tool/nfs-application-deploy-tool.text.gz

Format: HTML
Index: /usr/share/doc/nfs-application-deploy-tool/html/index.html
Files: /usr/share/doc/nfs-application-deploy-tool/html/*.html
